language: shell
matrix:
  fast_finish: true
  include:
    - name: "Python 3.6.8 on Windows test"
      os: windows
      language: shell
      env:
        - PATH="/c/Python36:/c/Python36/Scripts:$PATH"
      cache:
        directories:
          - $HOME/AppData/Local/pip/Cache
          - /c/Python36
      before_install:
        - | 
          if [[ ! -f /c/Python36/python ]]; then 
               choco install python --version=3.6.8
          fi
        - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"
        - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"
        - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
      install:
        - cd $TRAVIS_BUILD_DIR
        - pip3 install .
      before_script:
        - cmd.exe //C 'examples\scripts\dllscollector.bat'
        - cd $TRAVIS_BUILD_DIR/examples/rootfs/x86_windows/bin
        - unzip -Pinfected wannacry.bin.zip
        - unzip -Pinfected UselessDisk.bin.zip
        - unzip -Pinfected GandCrab502.bin.zip
        - unzip -Pinfected al-khaser.bin.zip
        - unzip -Pinfected sality.dll.zip
        - cd $TRAVIS_BUILD_DIR/tests
      script:
        - cmd.exe //C '.\test_pe.bat'
